enum DATE_FORMATS {
  DATE_WITH_KEBAB_CASE = "dd-MM-yyyy",
  DATE_WITH_BARS = "dd/MM/yyyy",
  DAY_AND_MONTH_WITH_BAR = "dd/MM",
}

enum MONTH_NUMBERS {
  JANUARY = "1",
  FEBRUARY = "2",
  MARCH = "3",
  APRIL = "4",
  MAY = "5",
  JUNE = "6",
  JULY = "7",
  AUGUST = "8",
  SEPTEMBER = "9",
  OCTOBER = "10",
  NOVEMBER = "11",
  DECEMBER = "12",
}

const MONTH_NAMES = {
  [MONTH_NUMBERS.JANUARY]: "Jan",
  [MONTH_NUMBERS.FEBRUARY]: "Fev",
  [MONTH_NUMBERS.MARCH]: "Mar",
  [MONTH_NUMBERS.APRIL]: "Abr",
  [MONTH_NUMBERS.MAY]: "Mai",
  [MONTH_NUMBERS.JUNE]: "Jun",
  [MONTH_NUMBERS.JULY]: "Jul",
  [MONTH_NUMBERS.AUGUST]: "Ago",
  [MONTH_NUMBERS.SEPTEMBER]: "Set",
  [MONTH_NUMBERS.OCTOBER]: "Out",
  [MONTH_NUMBERS.NOVEMBER]: "Nov",
  [MONTH_NUMBERS.DECEMBER]: "Dez",
};

enum WEEK_DAYS_NUMBER {
  SUNDAY = "1",
  MONDAY = "2",
  TUESDAY = "3",
  WEDNESDAY = "4",
  THURSDAY = "5",
  FRIDAY = "6",
  SATURDAY = "7",
}

const WEEK_DAYS_NAMES = {
  [WEEK_DAYS_NUMBER.SUNDAY]: "Domingo",
  [WEEK_DAYS_NUMBER.MONDAY]: "Segunda",
  [WEEK_DAYS_NUMBER.TUESDAY]: "Terça",
  [WEEK_DAYS_NUMBER.WEDNESDAY]: "Quarta",
  [WEEK_DAYS_NUMBER.THURSDAY]: "Quinta",
  [WEEK_DAYS_NUMBER.FRIDAY]: "Sexta",
  [WEEK_DAYS_NUMBER.SATURDAY]: "Sábado",
};

export {
  DATE_FORMATS,
  MONTH_NAMES,
  MONTH_NUMBERS,
  WEEK_DAYS_NAMES,
  WEEK_DAYS_NUMBER,
};
